name: musicapp
description: "A new Flutter project."

publish_to: 'none'


version: 1.0.0+1

environment:
  sdk: ^3.7.2


dependencies:
  flutter:
    sdk: flutter


  cupertino_icons: ^1.0.8
  get_it: ^8.0.3
  mobx: ^2.5.0
  flutter_mobx: ^2.0.6
  just_audio: ^0.10.3
  flutter_screenutil: ^5.9.3
  injectable: ^2.3.2

dev_dependencies:
  flutter_test:
    sdk: flutter


  flutter_lints: ^5.0.0
  build_runner: ^2.4.6
  mobx_codegen: ^2.4.0
 
  injectable_generator: ^2.4.1



flutter:

  
  uses-material-design: true


  assets:
    - assets/audios/   
    - assets/png/ 


  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700

